### ISSUE TITLE
Difference from qs

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/querystringparser#1]
``` js
var qsOld = require('qs');
var qs = require('querystringparser');

console.log(qs.parse('name=a+test')); // { name: 'a test' }
console.log(qsOld.parse('name=a+test')); // { name: 'a test' }

console.log(qs.parse({ 'test[name]': 'a+test' })); // { test: { name: 'a test' } }
console.log(qsOld.parse({ 'test[name]': 'a+test' })); // { test: { name: 'a+test' } }
```

I'm actually just relying on `qs`/`querystringparser` to resolve nested objects.

**Comment by petkaantonov** [comment]
Seems the same to me except `+` is decoded consistently?

**Comment by tjconcept** [comment]
I just thought this library was a drop-in replacement, but this gives me a bug in my software.

I'm actually using felixge/node-formidable to parse http body data, and then using `querystringparser` on the result to have objects nested - I might actually be decoding stuff twice?

**Comment by petkaantonov** [comment]
Where is the `qs` documentation for this?

**Comment by tjconcept** [comment]
I don't know, and I don't know if there is one.

**Comment by petkaantonov** [comment]
Ok it is probably intentional, I will change the behavior so that object values are not decoded

**Comment by tjconcept** [comment]
Okay, awesome, and thanks for the quick response.

**Comment by tjconcept** [comment]
You're the man! Don't forget to publish to NPM :)

**Comment by petkaantonov** [comment]
npm publish gives 500 error to me currently

**Comment by tjconcept** [comment]
Bummer..

**Comment by tjconcept** [comment]
Would you give it another shot?

**Comment by petkaantonov** [comment]
should be published now
